---
- name: Install localhost dependencies and required packages
  hosts: localhost
  become: true
  tags:
      - install
  roles:
      - installation

- name: Prepare Docker containers and set ns-3 configuration
  hosts: localhost
  become: true
  tags:
      - prepare
  roles:
      - preparation
     
- name: Execute localhost simulation
  hosts: localhost
  become: true
  tags:
     - execute
  roles:
      - execution

- name: Cleanup localhost simulation
  hosts: localhost
  become: true
  tags:
     - cleanup
  roles:
      - cleanup
     