---
# I didn't manage to get NS3 running directly from systemd script, this scriptis just used from systemd
- name: create launch NS3 script
  tags:
    - install
  template:
    src: templates/launch_ns3.j2
    dest: "{{ deployFolder }}/{{ nsVersion }}/{{ nsCodeFolder }}/launch_ns3.sh"
    owner: dockemu
    #group: dockemu
    mode: 0755

# COPY Dockerfiles AND BUILD IMAGES
- name: Copy Dockerfile for client nodes
  copy: "src=files/client/Dockerfile dest={{ deployFolder }}/client/"

- name: Copy wrapperfile for client nodes
  copy: "src=files/client/wrapper.sh dest={{ deployFolder }}/client/"

- name: Copy python script for client nodes
  copy: "src=files/client/client.py dest={{ deployFolder }}/client/"

- name: Copy pickle_cifar
  copy: "src=files/client/pickle_cifar dest={{ deployFolder }}/client/"

- name: Copy Dockerfile for server nodes
  copy: "src=files/server/Dockerfile dest={{ deployFolder }}/server/"

- name: Copy wrapperfile for server nodes
  copy: "src=files/server/wrapper.sh dest={{ deployFolder }}/server/"

- name: Copy python script for server nodes
  copy: "src=files/server/server.py dest={{ deployFolder }}/server/"

- name: Build client image and leave it in internal repository
  docker_image:
    build:
      path: "{{ deployFolder }}/client"
      pull: yes
    name: "{{ baseContainerName }}_client"
    source: build

- name: Build server image and leave it in internal repository
  docker_image:
    build:
      path: "{{ deployFolder }}/server"
      pull: yes
    name: "{{ baseContainerName }}_server"
    source: build

#CREATE LOG FOLDERS
- name: Creates log folders for each client node
  file:
    path: "{{ deployFolder }}/logs/{{ experimentName }}/logs/{{ baseContainerName }}-{{ item }}"
    state: directory
  with_sequence: "start=0 count={{ numberOfClientNodes }}"

- name: Creates log folders for each server node
  file:
    path: "{{ deployFolder }}/logs/{{ experimentName }}/logs/{{ baseContainerName }}-server-{{ item }}"
    state: directory
  with_sequence: "start=0 count={{ numberOfServerNodes }}"


  # NS3 CONF AND COMPILATION
- name: Copy NS3 configuration file
  copy: "src=files/{{ ns3NetworkScript }}.cc dest={{ deployFolder }}/{{ nsVersion }}/{{ nsCodeFolder }}/scratch"

- name: execute ./waf to build new ns3 configuration file
  command: ./waf
  args:
    chdir: "{{ deployFolder }}/{{ nsVersion }}/{{ nsCodeFolder }}"